name: Continuous Improvement

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: 'main'
      build:
        required: false
        type: string
        default: 'false'
      commit:
        required: false
        type: string
        default: 'false'
      tag:
        required: false
        type: string
        default: 'false'
      changelog:
        required: false
        type: string
        default: 'true'
      vcs_release:
        required: false
        type: string
        default: 'false'
      push:
        required: false
        type: string
        default: 'false'
    secrets:
      FACSIMILAB_BOT_SSHKEY:
        required: false
      FACSIMILAB_BOT_SSH_PUBKEY:
        required: false

permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Setup | Force correct release branch on workflow SHA
        run: git checkout -B ${{ inputs.ref }}

      - name: Python Semantic Release
        id: psr-ci
        uses: pranavmishra90/semvar-docker@v0.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_email: "195262995+facsimilab-bot@users.noreply.github.com"
          ssh_private_signing_key: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
          ssh_public_signing_key: ${{ secrets.FACSIMILAB_BOT_SSH_PUBKEY }}
          build: ${{ inputs.build }}
          changelog: ${{ inputs.changelog }}
          commit: ${{ inputs.commit }}
          tag: ${{ inputs.tag }}
          vcs_release: ${{ inputs.vcs_release }}
          push: ${{ inputs.push }}
          root_options: "-v"
