name: Demo-CI
on:
  push:
    branches:
      - main
      - rc
      - feat/*
  pull_request:
    branches:
      - rc
    types:
      - opened
      - assigned
      - labeled
      - ready_for_review

permissions:
  id-token: write
  contents: write
  pull-requests: read
  actions: read

jobs:
  ci:
    uses: facsimilab/central-workflows/.github/workflows/ci.yml@main
    with:
      ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
      build: "false"
      changelog: "true"
      commit: "false"
      tag: "false"
      vcs_release: "false"
      push: "false"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
      SSH_PUBLIC_KEY: ${{ secrets.FACSIMILAB_BOT_SSH_PUBKEY }}
